const projects = [
    {
        id: "spacenauts",
        title: "Spacenauts",
        description: "Spacenauts is a ipad game that challenges players to docking spaceship to space station with limited fuel and real physics movement.",
        longDescription: "Spacenauts is an immersive iOS game developed for the iPad that places players in the role of a spaceship pilot tasked with docking to a space station. The game emphasizes realistic physics, requiring players to carefully manage their limited fuel supply while navigating the challenges of space travel. Players must account for momentum, inertia, and gravitational forces as they attempt to align their spacecraft with the docking port.\n\n The game features multiple levels of increasing difficulty, each introducing new obstacles and tighter fuel constraints. The intuitive touch controls allow players to adjust their thrust and orientation, providing an engaging and educational experience about the principles of spaceflight. Spacenauts combines entertainment with learning, making it suitable for players of all ages interested in space exploration.",
        challenge: "Develop a final project for Apple Developer Academy that showcases skills in development, design thinking, and professional skills.",
        solution: "Developed an iOS game using Swift and RealityKit to create an engaging space docking experience with realistic physics.",
        impact: "Spacenauts has received positive feedback from exhibition visitor and usability test users.",
        features: [
            "Docking spaceship to space station with limited fuel",
            "Real physics movement",
            "3D environment",
        ],
        technologies: ["iOS", "Swift", "SwiftUI", "RealityKit", "SwiftData", "Blender"],
        image: "images/spacenauts.jpg",
        gallery: [],
        link: null,
        repo: null,
        team: "Team of 6",
        duration: "3 Months",
        type: "Mobile Game",
        aosDelay: 100,
        tags: ["iOS", "Swift", "RealityKit", "SwiftData", "Blender"],
        role: "iOS Developer",
        year: "2025"
    },
    {
        id: "pu-shy",
        title: "Pu.Shy",
        description: "Pu.shy is a beginner-friendly iOS app designed to be your virtual lifting partner. It helps new lifters build safe habits by detecting body movements and posture using your phone’s camera.",
        longDescription: "Pu.shy is an innovative iOS application tailored for individuals new to weightlifting. Recognizing that improper form is a leading cause of injury, Pu.shy leverages the power of CoreML and Vision frameworks to provide real-time feedback on your lifting posture. \n\n The app acts as a virtual spotter, analyzing your movements through the phone's camera and offering instant visual and haptic cues when your form deviates from the safe standard. Beyond just correction, Pu.shy tracks your progress over time, helping you build confidence and consistency in your fitness journey. The intuitive interface ensures that even those completely new to the gym can start lifting safely and effectively.",
        challenge: "Beginner weightlifters often struggle with proper form, leading to injuries and lack of confidence. Personal trainers are expensive, and existing apps often lack real-time feedback.",
        solution: "Developed an iOS app using Vision and CoreML to analyze body pose in real-time. The app provides instant visual and haptic feedback when the user's form deviates from safe parameters.",
        impact: "Empowered users to lift safely without a human spotter. The on-device processing ensures privacy while providing immediate, actionable feedback.",
        features: [
            "Real-time Posture Correction using Vision Framework",
            "Instant Haptic & Visual Feedback",
            "Progress Tracking & Workout History",
            "Beginner-friendly Interface",
            "Privacy-focused: All processing happens on-device"
        ],
        technologies: ["iOS", "Swift", "SwiftUI", "MLKit", "Vision", "CoreML", "CreateML"],
        image: "images/pu.shy.jpg",
        gallery: [],
        link: null,
        repo: null,
        team: "Team of 6",
        duration: "1 Months",
        type: "Mobile App",
        aosDelay: 100,
        tags: ["iOS", "Swift", "MLKit", "Vision", "CoreML", "CreateML"],
        role: "iOS Developer",
        year: "2025"
    },
    {
        id: "shiny-shift",
        title: "Shiny Shift",
        description: "ShinyShift: Auto-generate fair, efficient cleaning schedules—saved securely and ready to share with one click.",
        longDescription: "The District Cleaning Service Leader at Green Office Park wants to improve operational efficiency, as the current manual plotting method for assigning cleaning areas every two weeks is time-consuming, difficult to track, and makes fair distribution and quick adjustments challenging. Our solution leverages a greedy algorithm and SwiftData to automatically generate a fair and efficient area plotting schedule with a single click. This eliminates the need for manual assignment, ensures the schedule is safely stored locally to prevent data loss, and allows easy distribution to teams in a readable text format. This project was developed using Swift as the main programming language and SwiftUI for building a modern, responsive, and intuitive user interface on iOS. SwiftData was implemented to manage local data storage, ensuring that the generated schedules are saved securely and remain available offline. A custom greedy algorithm serves as the core logic for automatically assigning cleaning areas to teams, enabling efficient and fair distribution without manual input. These technologies were chosen to provide a fast, reliable, and user-friendly experience, while also minimizing the complexity of managing schedules. When the user taps the “Generate Schedule” button, the app uses the greedy algorithm to process area and team data, saves the result using SwiftData, then displays the schedule in a structured text format ready to be shared with the teams. This seamless flow helps the cleaning service lead automate scheduling tasks with just one click.",
        challenge: "Manual scheduling for cleaning teams was time-consuming, prone to errors, and often resulted in unfair workload distribution.",
        solution: "Implemented a greedy algorithm to automate schedule generation, ensuring fairness and efficiency. Used SwiftData for reliable local storage and offline access.",
        impact: "Reduced scheduling time from hours to seconds. Improved team satisfaction through fair workload distribution and easy schedule sharing.",
        features: [
            "Generate Schedule",
            "Randomized Team Assignment",
            "Fair Distribution",
            "Easy Distribution",
            "Offline Storage"
        ],
        technologies: ["iOS", "Swift", "SwiftUI", "SwiftData"],
        image: "images/shinyshift/shiny-shift.jpeg",
        gallery: ["images/shinyshift/image1.png", "images/shinyshift/image2.png", "images/shinyshift/image3.png", "images/shinyshift/image4.png", "images/shinyshift/image5.png", "images/shinyshift/image6.png", "images/shinyshift/image1.1.png", "images/shinyshift/image1.2.png", "images/shinyshift/image1.3.png"],
        link: null,
        repo: "https://github.com/mutakin-san/core-challenge-ada",
        team: "Team of 3",
        duration: "1 Month",
        type: "Mobile App",
        aosDelay: 100,
        tags: ["iOS", "Swift", "SwiftData"],
        role: "iOS Developer",
        year: "2025"
    },
    {
        id: "asanti",
        title: "Asanti",
        description: "An Android application that allows users to check the stunting status of babies and mom.",
        longDescription: "Asanti is a comprehensive Android application developed to combat stunting in children by empowering mothers with easy-to-use monitoring tools. The app provides a digital platform for tracking the growth and nutritional status of both babies and expectant mothers.\n\n Users can input key health metrics, which the app analyzes against standard growth charts to detect early signs of stunting or malnutrition. Asanti also serves as an educational hub, offering personalized nutritional advice, meal plans, and health tips approved by medical professionals. By bridging the gap between families and health resources, Asanti aims to ensure every child gets a healthy start in life.",
        challenge: "Stunting is a major health issue, often detected too late due to lack of accessible monitoring tools for parents.",
        solution: "Created an accessible Android app that allows parents to easily input growth data and receive instant analysis against standard growth charts.",
        impact: "Facilitated early detection of stunting risks, enabling timely intervention and better health outcomes for children.",
        features: [
            "Stunting Detection Algorithm",
            "Growth & Nutrition Tracking",
            "Personalized Health Recommendations",
            "Educational Articles & Resources",
            "User-friendly Dashboard for Mothers"
        ],
        technologies: ["Android", "Flutter", "Firebase", "Dart"],
        image: "images/asanti.png",
        gallery: [],
        link: null,
        repo: null,
        team: "Solo Developer",
        duration: "3 Months",
        type: "Android App",
        aosDelay: 100,
        tags: ["Android", "Flutter", "Firebase", "Dart"],
        role: "Android Developer",
        year: "2024"
    },
    {
        id: "luarkelas-academy",
        title: "Luarkelas Academy",
        description: "Luarkelas Academy is Fullstack website using Next.js that provides a platform for users to buy online courses and events.",
        longDescription: "Luarkelas Academy is a modern, full-stack ed-tech platform built to democratize access to quality education. Developed using Next.js for high performance and SEO, the platform connects learners with expert instructors through a seamless course marketplace.\n\n The platform features a robust payment gateway integration for secure transactions, a dynamic dashboard for students to track their learning progress, and an instructor portal for course management. With a focus on user experience, Luarkelas Academy offers a responsive design that works perfectly across all devices, ensuring learning can happen anywhere, anytime.",
        challenge: "Building a scalable and SEO-friendly platform for online courses with secure payment processing.",
        solution: "Utilized Next.js for server-side rendering and SEO. Integrated a secure payment gateway and built a robust backend with PostgreSQL and Prisma.",
        impact: "Provided a seamless learning experience for students and a powerful management tool for instructors, increasing course accessibility.",
        features: [
            "Secure Payment Gateway Integration",
            "Dynamic Course Management System",
            "User Dashboard & Progress Tracking",
            "Responsive & SEO Optimized Design",
            "Real-time Event Registration"
        ],
        technologies: ["Next.js", "React", "TypeScript", "Tailwind CSS", "PostgreSQL", "Prisma", "Web"],
        image: "images/luarkelas_academy.png",
        gallery: [],
        link: null,
        repo: null,
        team: "Fullstack Developer",
        duration: "2 Months",
        type: "Web App",
        aosDelay: 200,
        tags: ["Next.js", "React", "Tailwind", "TypeScript"],
        role: "Fullstack Developer",
        year: "2024"
    },
    {
        id: "predikter",
        title: "Predikter",
        description: "Predikter is an Android application that allows users to predict the cattle body weight & selling price based on their body size.",
        longDescription: "Predikter is a specialized Android tool designed to assist cattle farmers and traders in making informed economic decisions. By utilizing augmented reality, the app can estimate the weight and fair market value of cattle simply by analyzing input data regarding their body dimensions.\n\n This tool eliminates the need for expensive and cumbersome weighing scales in the field. It provides instant, accurate estimates that help prevent financial loss and ensure fair trade. The app also maintains a history of predictions, allowing farmers to track the growth and value appreciation of their livestock over time.",
        challenge: "Farmers lacked an easy way to estimate cattle weight and price in the field without expensive equipment.",
        solution: "Integrated augmented reality into an Android app to predict weight and price based on simple body measurements.",
        impact: "Enabled farmers to make informed economic decisions and ensure fair trade without needing heavy equipment.",
        features: [
            "Augmented Reality Weight Prediction",
            "Real-time Market Price Estimation",
            "Offline Functionality",
            "Historical Data Tracking",
            "Simple Data Entry Interface"
        ],
        technologies: ["Flutter", "Dart", "Augmented Reality", "Clean Architecture", "MVVM"],
        image: "images/predikter.png",
        gallery: [],
        link: "https://play.google.com/store/apps/details?id=com.kimdev.predikter",
        repo: "https://github.com/mutakin-san/predikter",
        team: "Solo Developer",
        duration: "1 Month",
        type: "Android App",
        aosDelay: 300,
        tags: ["Flutter", "Dart", "Augmented Reality", "Clean Architecture", "MVVM"],
        role: "Flutter Developer",
        year: "2024"
    },
    {
        id: "ditonton",
        title: "Ditonton",
        description: "Ditonton is an Android application that allows users to watch movies and TV series.",
        longDescription: "Ditonton is a sleek and feature-rich movie discovery application built with a focus on Clean Architecture and modular design. It integrates with the TMDB API to provide users with up-to-date information on thousands of movies and TV shows.\n\n The app features a robust search engine, personalized watchlists, and detailed information screens including cast, reviews, and trailers. Under the hood, Ditonton demonstrates best practices in modern Android development, utilizing dependency injection, reactive programming, and a clear separation of concerns to ensure scalability and testability.",
        challenge: "Creating a maintainable and scalable Android app that handles complex data flows and API interactions.",
        solution: "Implemented Clean Architecture with modular design, using Dagger Hilt for dependency injection and RxJava for reactive programming.",
        impact: "Resulted in a highly testable and maintainable codebase, serving as a reference for best practices in Android development.",
        features: [
            "Clean Architecture & Modular Design",
            "TMDB API Integration",
            "Offline Caching & Watchlist",
            "Search & Filter Functionality",
            "Unit & UI Testing Coverage"
        ],
        technologies: ["Android", "Flutter", "Dart", "CI/CD", "BLoC State Management", "Get It"],
        image: "images/ditonton.png",
        gallery: [],
        link: "https://github.com/mutakin-san/ditonton",
        repo: "https://github.com/mutakin-san/ditonton",
        team: "Solo Developer",
        duration: "1 Month",
        type: "Android App",
        aosDelay: 400,
        tags: ["Android", "Flutter", "Dart", "Clean Architecture", "CI/CD", "BLoC State Management", "Get It"],
        role: "Flutter Developer",
        year: "2023"
    },
    {
        id: "cypher-city-sfc",
        title: "Cypher City SFC",
        description: "Cypher City SFC is an Android application for managing competitions.",
        longDescription: "Cypher City SFC is a dedicated management platform designed to streamline the organization of sports and e-sports competitions. It serves as a central hub for organizers, participants, and spectators to stay updated on tournament schedules, scores, and standings.\n\n The app simplifies complex logistics such as bracket generation, team registration, and real-time score reporting. With its intuitive MVVM architecture, the app ensures a smooth and responsive user experience, handling real-time data updates efficiently to keep everyone in the loop during high-stakes events.",
        challenge: "Managing tournament logistics and real-time updates for multiple stakeholders was chaotic and inefficient.",
        solution: "Built a centralized management platform with real-time database integration to sync scores and schedules instantly.",
        impact: "Streamlined tournament operations and improved the experience for organizers, participants, and spectators.",
        features: [
            "Tournament Bracket Management",
            "Team Registration & Management",
            "Real-time Score Updates",
            "Event Scheduling & Notifications",
            "MVVM Architecture Pattern"
        ],
        technologies: ["Android", "Flutter", "Dart"],
        image: "images/cyphercity.png",
        gallery: [],
        link: "https://github.com/mutakin-san/cyphercity",
        repo: "https://github.com/mutakin-san/cyphercity",
        team: "Solo Developer",
        duration: "2 Months",
        type: "Android App",
        aosDelay: 500,
        tags: ["Android", "Flutter", "Dart"],
        role: "Flutter Developer",
        year: "2023"
    },
    {
        id: "valo-ai",
        title: "Valo.AI",
        description: "Valo.AI is an Android application to recommend vaccines location and types based on user.",
        longDescription: "Valo.AI is a public health initiative app designed to increase vaccine accessibility and awareness. It uses geolocation services to recommend the nearest vaccination centers and appropriate vaccine types based on the user's profile and location.\n\n The app integrates with map services to provide turn-by-turn navigation to clinics. It also features an intelligent recommendation engine that considers user age, health history, and local availability to suggest the most suitable vaccination options, helping to streamline the public health response.",
        challenge: "People struggled to find appropriate vaccination centers nearby that matched their specific health needs.",
        solution: "Developed a location-based recommendation engine that suggests vaccine centers based on user profile and proximity.",
        impact: "Improved vaccine accessibility and helped users find the right care facilities quickly and easily.",
        features: [
            "Location-based Vaccine Center Finder",
            "Personalized Vaccine Recommendations",
            "Google Maps Integration",
            "User Health Profile Management",
            "Appointment Scheduling Support"
        ],
        technologies: ["Android", "Kotlin", "Google Maps API", "Location Services", "Room Database"],
        image: "images/valoai.png",
        gallery: [],
        link: "https://github.com/mutakin-san/valo.ai",
        repo: "https://github.com/mutakin-san/valo.ai",
        team: "Team of 4",
        duration: "1.5 Months",
        type: "Android App",
        aosDelay: 600,
        tags: ["Android", "Kotlin", "Maps API"],
        role: "Android Developer",
        year: "2023"
    }
];
